### ISSUE TITLE
Make a new release from source (API Key)

### ISSUE THREAD

**Issue by dweber019** [Vheissu/aurelia-google-maps#103]
Currently I get:
```
ERROR [aurelia-google-maps] No API key or client ID has been specified.
```
This has already been fixed in
https://github.com/Vheissu/aurelia-google-maps/blob/master/src/google-maps.ts#L85

But was not released or build
https://github.com/Vheissu/aurelia-google-maps/blob/master/dist/commonjs/google-maps.js#L67

Please release / build a new version with the fix.

**Comment by VMBindraban** [comment]
They force a key since today.

**Comment by danielmihaylov** [comment]
> Currently I get:
> 
> ```
> ERROR [aurelia-google-maps] No API key or client ID has been specified.
> ```
> 
> This has already been fixed in
> https://github.com/Vheissu/aurelia-google-maps/blob/master/src/google-maps.ts#L85
> 
> But was not released or build
> https://github.com/Vheissu/aurelia-google-maps/blob/master/dist/commonjs/google-maps.js#L67
> 
> Please release / build a new version with the fix.

Did you fix it/ release it, i am still getting this error ?

**Comment by EtseDev** [comment]
Hi @Vheissu 

Would this fix be released anytime soon?
