### ISSUE TITLE
common.js:197 Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by ghost** [Vheissu/aurelia-google-maps#12]
I get this error anytime the bounds change (either latitude and longitude variables updated or dragging or zooming the map.

**Comment by Vheissu** [comment]
Sit tight, this might be fixed with the upcoming release with a great PR from @tomtomau

**Comment by Vheissu** [comment]
Give the latest release a try and if it doesn't work, feel free to log an issue again.
