### ISSUE TITLE
map.css is missing

### ISSUE THREAD

**Issue by qamaruddin** [Vheissu/aurelia-google-maps#20]
I have recently installed and configured the plugin as instructed. However I am getting a 404 not found while css is being loaded. I think something wrong with the url as the css file url seems to have a .js extensions

http://localhost:9000/jspm_packages/npm/aurelia-google-maps@1.0.8/maps.css.js

**Comment by Vheissu** [comment]
Weird. I am not seeing this happen locally. What version of Jspm are you using?

**Comment by hex1848** [comment]
I was seeing this as well.  Running jspm update seemed to fix the issue for me.
