### ISSUE TITLE
wrong in plugin config

### ISSUE THREAD

**Issue by ndtuan412** [Vheissu/aurelia-google-maps#24]
I have just updated to v1.0.10 and my app says error: `.../jspm_packages/npm/aurelia-google-maps@1.0.10/aurelia-google-maps.js 404 (Not Found)`

Have a look in `index.js` of the plugin, I see: `define(['exports', './aurelia-google-maps'], function (exports, _aureliaGoogleMaps) {`
Try change to `define(['exports', './configure'], function (exports, _aureliaGoogleMaps) {` and new error: `Unhandled rejection Error: No Aurelia APIs are defined for the element: "GOOGLE-MAP"`

I tested with v1.0.9, everything is OK.

**Comment by hex1848** [comment]
Had the same issue with 1.0.11.  As a work around, I diffed jspm_packages\npm\aurelia-google-maps@1.0.09 with jspm_packages\npm\aurelia-google-maps@1.0.11 and copied over everything except the google-maps.js file.  The css and html files are missing entirely, and the index and configure files are different between the packages.  I really needed the auto-zoom functionality and this helped me get it working..  Hopefully this will get fixed in 1.0.12?

**Comment by Vheissu** [comment]
Sorry about this, this is an issue with the plugin structure I was using.

**Comment by ne0guille** [comment]
Im having this issue with both v.1.0.9 and 1.0.11, can you share the correct plugin structure? im using the one from the readme and its failing

**Comment by rborosak** [comment]
Are there any updates to this problem?
@hex1848 solution works for me

**Comment by egeland** [comment]
I edited `index.js` to say `define(['exports', './google-maps'],`, rather than `define(['exports', './aurelia-google-maps'],`, and it seems happier... (I'm in the middle of a bundling nightmare, so I haven't tested it properly, though)

**Comment by Vheissu** [comment]
A new release is coming out which addresses issues like above. It'll be out today.

**Comment by ghost** [comment]
@Vheissu I know you're a busy guy. Any update on the new release??

**Comment by Vheissu** [comment]
@b-rays Just put out the latest release. Please tell me if this fixes the issues for you. The structure of how everything is built has changed, simplified tooling. Tests are also coming shortly.

**Comment by ghost** [comment]
@Vheissu It's not working for me. I'm getting a 304 to the aurelia-google-maps@1.0.13.js and no API calls in my Google Developer Console. I could be doing something wrong. Someone else give it a go.

**Comment by Vheissu** [comment]
This should no longer be an issue in 1.0.16.

**Comment by bsrdjan** [comment]
Getting the same error with version 2.0 and aurelia-cli, only with production builds.

The `au run --env dev` runs fine and `au run --env prod` results in 

 `No Aurelia APIs are defined for the element: "GOOGLE-MAP".`
