### ISSUE TITLE
option to disable mouse-wheel zoom functionality

### ISSUE THREAD

**Issue by tareqimbasher** [Vheissu/aurelia-google-maps#26]
We need a way to disable the zoom functionality that occurs when you use the mousewheel over the map. it can get annoying in certain instances when scrolling the page and the mouse falls on the map, your current page scroll is stopped and instead the map is zoomed out.

Thank you

**Comment by bartlenaerts** [comment]
Yes. I've integrated this in version 1.0.15. Use `options` as an extra property in the `config.options` method.

``` javascript
aurelia.use.plugin('aurelia-google-maps', config => {
  config.options({
    apiKey: 'myapiKey',
    apiLibraries: 'drawing,geometry',
    options: { scrollwheel:  false }
  });
});
```

**Comment by Vheissu** [comment]
Release 1.0.16 has this, closing.
