### ISSUE TITLE
How to access map object within view-model?

### ISSUE THREAD

**Issue by ghost** [Vheissu/aurelia-google-maps#47]
I'm having trouble working out how to access the current map object from within a .ts file to draw a polygon. I'm using Aurelia (Aurelia-CLI) and TypeScript. How would I go about drawing a polygon on the map?

**Comment by ghost** [comment]
Fixed thanks to @VMBindraban

**Comment by jimisens** [comment]
Hello, 
I trying to do  the same thing. With the api:loaded event i'm available to call the drawingManager but i need to access the current map object. How can i to this please ?? 
Thank you very much.

**Comment by ghost** [comment]
https://gitter.im/Vheissu/aurelia-google-maps?at=589af30f872fc8ce620ab61a

Try and follow this.
