### ISSUE TITLE
Traffic layer

### ISSUE THREAD

**Issue by arvadevy** [Vheissu/aurelia-google-maps#50]
Does anyone know how to add the traffic layer?
[Google Maps Traffic Layer](https://developers.google.com/maps/documentation/javascript/examples/layer-traffic)
and how to refresh it every 15 minutes or something?

**Comment by ghost** [comment]
Access the maps object by adding the view-model.ref attribute to the <google-map> element, like so:

     <google-map view-model.ref="maps"></google-map>

So maps is now available for use in the viewmodel. Then simply follow the instructions in the Traffic Layer docs on Google: https://developers.google.com/maps/documentation/javascript/examples/layer-traffic

As a sidenote: you may have to subscribe to the 'googlemap:infowindow:domready' event and do your logic inside there to make sure everything is loaded.

**Comment by arvadevy** [comment]
Maybe add this to the documentation? Anyway thanks!

**Comment by hancsu** [comment]
Yeah it would be useful in the docs, I only found out by asking on Gitter.

**Comment by ghost** [comment]
Yeah it would be useful in the docs, I only found out by asking on Gitter.

You should close the issue if your question has been answered.

EDIT: As a sidenote, if you are using TypeScript and start getting red underlines when using 'google.maps' then get the Google Maps typings: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/googlemaps

**Comment by justindra** [comment]
@arvadevy You can also set it as a parameter in the HTML

https://github.com/Vheissu/aurelia-google-maps#map-type
