### ISSUE TITLE
Feature request / question: Expose the map object once created.

### ISSUE THREAD

**Issue by gpetrioli** [Vheissu/aurelia-google-maps#52]
Is there a plan to expose the `map` object of the created map somehow, so we can manipulate the map beyond what is currently available by the plugin?

**Comment by VMBindraban** [comment]
Did you try `view-model.ref`?

http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-basics/5

**Comment by gpetrioli** [comment]
@VMBindraban Is it safe to assume that in the `attached()` method of the view where the `<google-map>` appears, the referenced variable will be available as `this.varname` ? (*it works locally*)

(*or could an async call make the variable be unready*)

**Comment by VMBindraban** [comment]
Yes.

Note that `varname` is set before google is loaded.

```js
this.subscription = this.eventAggregator.subscribe('googlemap:api:loaded', () => {
  ...
});
```

**Comment by gpetrioli** [comment]
Thanks for the help/info!
