### ISSUE TITLE
Question: How to use generic npm package that adds google map utilities ?

### ISSUE THREAD

**Issue by gpetrioli** [Vheissu/aurelia-google-maps#55]
Is it possible to use other google map utilities with this plugin ?

I want to use the InfoBox utility (https://www.npmjs.com/package/google-maps-utility-library-v3-infobox). 

I add it to aurelia, but a list of 
> google is not defined

shows in the console (*when running the app, the build goes fine*). 

And when i import it and try to use it i get a 
>TypeError: _googleMapsUtilityLibraryV3Infobox is undefined

Have any hints on how to use this utility with your plugin ? 

(*apologies if this is way too OT*)

**Comment by ghost** [comment]
Sounds like you don't have the Google Maps typings installed. You need to download the type definition files so that TypeScript knows what the types are. 

When you say you "add it to Aurelia", which method did you use to include it?

**Comment by gpetrioli** [comment]
@hancsu I am not using TypeScript, just plain JS.
I installed the google-map-utility-library-v3-infobox through npm with the --save param and updated the aurelia.json to include it in the vendor bundle (_as other dependencies_).

Then i import it with `import {InfoBox} from "google-maps-utility-library-v3-infobox";`

I curerrently have worked around it by defining the InfoBox plugin in the actual VM when the `map-loaded` event triggers.
