### ISSUE TITLE
Callback Issue

### ISSUE THREAD

**Issue by ggrimbert** [Vheissu/aurelia-google-maps#56]
Hi,

I have a problem with your component. 
The callback passed to Google is called 5 seconds after the API is loaded...
I mean that all calls to Google are made, the API is loaded but it takes 5 seconds to call back my code, so it's unusable.

I've tried on my way, not passing the callback to Google but defined it on the script tag directly, I don't have timing issue.

Is there a way to change it, or a parameters that makes all faster ?

**Comment by Vheissu** [comment]
Subsequent releases should have fixed this due to relying on lower level API and less abstraction.
