### ISSUE TITLE
Change line endings to work on mac without additional git config?

### ISSUE THREAD

**Issue by Tyderion** [Vheissu/aurelia-google-maps#57]
Hey there

I started using your plugin today and realized, that i need to implement some additional features for our usecase and I wanted to open PRs for those but...

When trying to open a PR I realized, that your files are not encoded in utf-8 but in some other encoding. I cannot get my development tools (e.g. visual studio code or sublime text) to save the file in the correct encoding.
If I open a pullrequest the diff of e.g the file google-maps.ts is the complete file, because the file is encoded differently which makes the PR pretty useless...

What do you think about changing the encoding to utf-8?

I could open a PR which would change every file to utf-8 and then after that I could open PRs for new features.

**Comment by drub0y** [comment]
That's weird... I had no problem working on it in VS Code (on Windows) when I contributed. I just opened it again real quick and VS Code is showing `google-maps.ts` as UTF-8 here. You sure you don't have something else messing with your files?
![snip_20170302093059](https://cloud.githubusercontent.com/assets/284152/23519215/03a19b16-ff2b-11e6-9e34-e59588eb748b.png)

**Comment by Tyderion** [comment]
On windows it works for me as well.

If I open it on my mac, it shows "UTF-8" as well but the file is displayed as having changed and when I save, git displays every line as removed and readded.
It still displays them as UTF-8 (in both windows and mac).
I have no idea why my visual studio code automatically performs some sort of conversion on mac, i'll test it on a coworkers mac to see if it is just something in my configuration.

I made a mistake in the PR though: the files are encoded wrongly because a leftover setting in .vscode/settings i forgot to remove.

I'll come back to this tomorrow after checking this and either updating or closing the PR

**Comment by drub0y** [comment]
Ah, I'm pretty sure that's a problem with git and line endings. This repo does not have a `.gitattributes` file to explicitly control line endings (it also uses an `.editorconfig` that explicitly sets line endings to `CRLF`). I would bet on non-Windows what's happening is that it's pulling down CRLF from the repo, changing to LF and then everything is showing as changed.

The real fix is to add a `.gitattributes` that explicitly sets `* text=CRLF` if that's what @Vheissu wants to be the standard for this repo. That would help non-CRLF native OS's (i.e. everything except Windows 😄) get this right.

**Comment by Tyderion** [comment]
Oh right, thanks @drub0y It was the line endings. adding `* text=CRLF` to .gittattributes didn't actually change anything though. 
I think the problem is the following:
- git checks out the files with LF line endings on mac
- .editorconfig is set to CRLF

So vscode saves the file with crlf endings even though git autoconverts

The fix is the a configuration for git on mac (which I think I forgot when I configured my laptop a few weeks back): `git config --global core.autocrlf input`

- git will still change the lineendings to unix when checking out on a mac.
- vscode will still overwrite all fileendings with CRLF when saving a file
Git will display a message when running `git diff`: 
```
warning: CRLF will be replaced by LF in src/google-maps.ts.
The file will have its original line endings in your working directory.
```
And the diff is empty which is what I wanted in the first place.

Thanks for the tip with the line endings @drub0y 

So judging from the git warning, the files are actually LF on github (as git on windows does by default) but .editorconfig specifies crlf which makes vscode (with the plugin) write crlf.

A different working solution would be to set `end_of_line = lf` in .editorconfig and let git handle all conversions.

I think that would be the cleanest solution because it should work with the default git config on macs and windows. What do you @Vheissu think about this?
