### ISSUE TITLE
Feature request: Set map view to a LatLngBounds

### ISSUE THREAD

**Issue by egeland** [Vheissu/aurelia-google-maps#6]
It would be great to have a way to either (or both) set the map view to be the area within which all the markers are, or an arbitrary [LatLngBounds](https://developers.google.com/maps/documentation/javascript/3.exp/reference#LatLngBounds) object.

The `fitBounds()` method on the [Map](https://developers.google.com/maps/documentation/javascript/3.exp/reference#Map) seems to be what we'd need to play with here..

**Comment by egeland** [comment]
I will need this very soon, so I'll "scratch my own itch" and get it done; I'm proposing to do it this way:
Find an appropriate place to pass an option of (something like) `zoomToBounds`, along with the markers.
If that is set to `true`, then generate a LatLngBounds object based on all the markers, and set the map view area to this, with the `fitBounds()` mentioned earlier.
If `zoomToBounds` is `undefined`, `null` or `false` we retain the current behaviour.

Ideas? Objections?

**Comment by egeland** [comment]
Gosh... "soon" is taking longer than I initially thought - but I _will_ get to this! :wink: 

EDIT: Oooh, #22 looks like it covers it already!

**Comment by tomtomau** [comment]
With #22 and #30 I think this case should be well covered.

#30 allows you to set some map defaults so that if there are no map markers present, it will fallback to the latitude, longitude and zoom specified.
