### ISSUE TITLE
feature: Add ability to draw polygons on the map itself

### ISSUE THREAD

**Issue by justindra** [Vheissu/aurelia-google-maps#60]
@Vheissu I'm planning on working on a feature that allows users to add in some polylines/polygons on top of the map, but just wanted to ask if you think this should be part of this plugin or if you feel like this should be a separate component that extends this plugin.

**Comment by ghost** [comment]
Would it be any different to just grabbing the map object and drawing the polylines the usual way?

**Comment by justindra** [comment]
Basically just using the usual way, but I thought we could possibly expose some of the controls through the parameter bindings instead of having to do it outside of the component.

**Comment by ghost** [comment]
Yeah that would have been useful to me a couple of months ago

+1 :+1:

**Comment by justindra** [comment]
@hancsu Have started on this feature. Any feedback, let me know.

https://github.com/justindra/aurelia-google-maps/tree/add-polygons

**Comment by justindra** [comment]
Will close this as its now implemented since this PR

https://github.com/Vheissu/aurelia-google-maps/pull/74
