### ISSUE TITLE
Proposal: Markers should only be an array of {lat, lng} and not Address/Geocoding

### ISSUE THREAD

**Issue by tomtomau** [Vheissu/aurelia-google-maps#66]
Since #59, I've been fixing up a few issues related to address markers and I'm proposing that we remove them in place of suggesting users move to accessing the GoogleMaps service (#64) directly and geocoding the address themselves (and handling rejections in user-land)

Currently one of the issues I'm facing is the extra layer of complexity that `validMarkers` adds to determining the markers to layout and when working with these issues I'm realising this is putting more burden on the `<google-map>` plugin than is necessary.

Fundamentally, my belief is that we should aim to be a simple layer between the Aurelia user and the Google Javascript API as much as possible. With exposing the Google Maps service in (#64) we should be able to keep the `<google-map>` component simpler by binding in markers which are as close to what the Javascript library expects etc.

In an unrelated note, @justindra and I are working with polygons at the moment with the plugin in our fork, but we're taking the same approach to binding in data which is closest to the Google Maps Javascript API.

I'm going to tidy up #64 ready for merge over the weekend but will try and put together another PR which outlines my proposal.

**Comment by Vheissu** [comment]
Closing this one as @tomtomau implemented this in a PR a while ago.
