### ISSUE TITLE
multiple maps cause an error

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [Vheissu/aurelia-google-maps#71]
I have two <google-map> and I'm having the following error.

```
<google-map></google-map>
<google-map></google-map>
```

```
You have included the Google Maps API multiple times on this page. This may cause unexpected errors.
 at js?key=omitted&libraries=geometry&callback=myGoogleMapsCallback:99
```

Two instances are created for the two maps and *loadApiScript()* is called twice on each instance.

Since both *window.google* and this._scriptPromise are undefined at the moment, *loadApiScript()* tries to load Google Maps API twice and gets error.

Any idea for fix?

**Comment by Vheissu** [comment]
This should have been fixed with subsequent changes including the use of an API class that better handles instances of Google Maps.

**Comment by HIRANO-Satoshi** [comment]
@Vheissu Thanks. I confirmed.
