### ISSUE TITLE
Address binding

### ISSUE THREAD

**Issue by mttmccb** [Vheissu/aurelia-google-maps#73]
Unless I'm missing something very obvious this doesn't appear to be implemented although it's in the docs, I've hunted the source code for a reference to `address` but it doesn't appear to be there.

I'm getting the address from an API call and then binding that to the maps component but it's just in the middle of the ocean.

**Comment by serifine** [comment]
I was wondering the same. It appears to be removed in these two merges:
https://github.com/Vheissu/aurelia-google-maps/commit/1010d04af9ea303726cfae8bb9eb5391656ed477
https://github.com/Vheissu/aurelia-google-maps/commit/efc6445b6f6d4e2cfd19a76829630d50e98fd38b

**Comment by tomtomau** [comment]
Correct, we removed this in favour of using the GoogleMapsAPI to geocode an address. In a reasonable UX you're likely to have multiple results for the search query and the user may want to select one. You'll receive the latitude and longitude which you can then bind into the component.

Apologies on it still remaining in the docs, I've raised a pull request at #75

**Comment by Vheissu** [comment]
This has been merged in. I'll get this released ASAP.

**Comment by Vheissu** [comment]
Released in version 2.1.0.
