### ISSUE TITLE
map reference undefined in map-loaded.call

### ISSUE THREAD

**Issue by sizilium** [Vheissu/aurelia-google-maps#77]
`<google-map markers.bind="markers" auto-update-bounds="true" map-loaded.call="mapLoadedCallback(map, $event)"></google-map>`

```
private mapLoadedCallback(map, event): void {
    console.log(map);
    console.log(event);
}
```

Result:
undefined   <----
Ag {gm_bindings_: {…}, __gm: Rf, gm_accessors_: {…}, panControl: true, panControlOptions: {…}, …}

**Comment by Vheissu** [comment]
@sizilium Can you please try the latest release and tell me if this is still an issue?

**Comment by sizilium** [comment]
I tested it with 2.1.0.
The map reference is still undefined in the mapLoadedCallback().
Note: I'm using TypeScript, but that should not make a difference...

As a workaround I can use Aurelias 'ref' feature (or jQuery) but it would be nice to have the reference to map through the event arg.

Thanks

**Comment by Vheissu** [comment]
@sizilium No worries. I'll see if I get time today/tomorrow to knock out a solution for this.

**Comment by airboss001** [comment]
This is old, but apparently the $events is ignored and the map gets placed in events param with the map param is set to null.

So I guess the moral of the story is, only pass the map.
