### ISSUE TITLE
Feature: Add support for google heatmaps or marker clusters?

### ISSUE THREAD

**Issue by bliu886** [Vheissu/aurelia-google-maps#78]
Having the ability to create heatmaps or have the markers cluster would be useful similar to the following:

https://developers.google.com/maps/documentation/javascript/marker-clustering

https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap

**Comment by tomtomau** [comment]
Marker clustering would be awesome, we may need to do this on our project in the near future so it may come down the wire but you're welcome to contribute to the repo yourself :)

**Comment by Vheissu** [comment]
Time permitting, let me see how much time I have to have a stab at this.

**Comment by VMBindraban** [comment]
I also would like to see this. I am almost hitting the 1.000 markers on the map.

**Comment by VMBindraban** [comment]
I will work on this feature, PR coming soon.

**Comment by Vheissu** [comment]
Fixed in the latest release, thank you @VMBindraban
