### ISSUE TITLE
Feature request: Info Windows

### ISSUE THREAD

**Issue by egeland** [Vheissu/aurelia-google-maps#8]
Would be great to be able to open an [info window](https://developers.google.com/maps/documentation/javascript/infowindows) when a marker is clicked, for example.

**Comment by tomtomau** [comment]
Not sure how this would be best executed within Aurelia (like generating HTML) - I know there's a way to render templates on the fly algorithmically, which might be the way to go.

**Comment by Vheissu** [comment]
Thanks to the work of a submitter, the recent release has this feature. Let me know if there are any issues.

**Comment by sboyd** [comment]
Hello all!! Thanks for the awesome plugin.
Is there a way to programmatically display the info window on click? I need to dynamically create the info window  just incase there's more than one item for a given map marker.

Thank! --Steve Boyd
