### ISSUE TITLE
Feature: Add support of clientId settings

### ISSUE THREAD

**Issue by alexanderozerov** [Vheissu/aurelia-google-maps#84]
Is there any way to use plugin with google maps premium plan if there is clientId and clientSecret instead of apiKey?

**Comment by Vheissu** [comment]
Do you have a link to the premium plan stuff? Happy to look into it.

**Comment by VMBindraban** [comment]
https://developers.google.com/maps/premium/overview

>Instead of an API key, you can use your client ID to make requests to any of the APIs **except** the following: Google Places API, Google Maps Geolocation API, Google Maps Roads API, and the Mobile APIs (Android, iOS).
