### ISSUE TITLE
Bug: initDrawingManager (google-maps.ts)

### ISSUE THREAD

**Issue by yelenatph** [Vheissu/aurelia-google-maps#87]
After putting marker from Drawing control on the map there is an uncaught error:
Uncaught TypeError: evt.overlay.getPath is not a function (see attached files)

Seems in initDrawingManager() method there is no check for evt.type. 
In case of evt.type == "polygon" there is no error (because it has paths), but in case of evt.type == "marker" there is an error , since marker hasn't getPath() method.
![markerbug](https://user-images.githubusercontent.com/36225554/35910446-41336270-0bff-11e8-9562-0c8902184ab4.JPG)
![markerbugincode](https://user-images.githubusercontent.com/36225554/35910448-41528b5a-0bff-11e8-99d7-4e6e457556db.JPG)

**Comment by Vheissu** [comment]
PR has been merged for this, thanks again. Minor release coming out soon.
