### ISSUE TITLE
Clearing ClusterMarkers not working

### ISSUE THREAD

**Issue by airboss001** [Vheissu/aurelia-google-maps#92]
It seems to just be adding clustered markers and never removing them when the marker array is changed.

google-maps.ts clearMarkers does some empty array thing using renderClusters that is apparently ineffective.

From what I can determine it looks like in marker-clustering.ts in the renderClusters function it is never saving the returned object so that the clearMarkers() can be called on the created overlay to actually remove the previously displayed clusters.

**Comment by airboss001** [comment]
I created a fork with changes that correct this issue, and I also found that it was calling renderClusters for each marker added instead of after the marker entries had completed so corrected that. I sure it could perhaps be done in a better fashion as I am a neanderthal with promises, but it is working for me and my case
https://github.com/airboss001/aurelia-google-maps.

**Comment by VMBindraban** [comment]
Can you submit a PR with the changes?

**Comment by airboss001** [comment]
I have several days ago. Not sure its the correct way as it also includes the rebuilt dist, besides the changes to the source google-maps.ts and marker-clustering.ts

**Comment by VMBindraban** [comment]
Whoops, missed that one.

**Comment by airboss001** [comment]
No worries, let me know if I need to change anything.
