### ISSUE TITLE
Polygons and Polylines

### ISSUE THREAD

**Issue by airboss001** [Vheissu/aurelia-google-maps#94]
So I had the need for generating polylines for from/to markers.
The current setup just used polygons and due to the fact that I could have many thousands of lines being drawn did not want to have it done with closed polygons for performance as well as visual effect of darking the semi-transparent lines due to doubling them up. (Admin visualization tool for template assignment and their distribution in the world over at FSEconomy.net)

Since the polygon and polyline code was mostly common, I refactored that out and created a couple of configuration classes that contained the needed parameter changes for those differences.

Currently the max displayed polylines I have had is around 6500, and with clustered markers is still very responsive.

Not sure if this is something you want in the project, but if so I can submit it.

You can review it over at:
https://github.com/airboss001/aurelia-google-maps/tree/Polylines

**Comment by jonaspu** [comment]
I'm sorry for hijacking your issue.

But since you seem to understand how the polylines work, could you explain to me how I can draw polylines on the map?

I tried binding `polylines` but it doesn't seem to work.

**Comment by airboss001** [comment]
The link provided above goes to the project with the polyline addition.

Check that out and see if it answers your question on one way of doing it.

**Comment by airboss001** [comment]
Here is how I use it in the HTML, and the code that builds out the lines and markers.

```
    <div >
        <google-map view-model.ref="mymap" map-loaded.call="mapLoaded(map, $event)" zoom="2" auto-update-bounds="true" markers.bind="myMarkers" polylines.bind="myLines" polygons.bind="myPolygons" style="width: 1280px; height: 1024px;"></google-map>
    </div>
```

```
this.api.getAllData(this.templateId).then(response =>
            {
                this.myMarkers = null;
                
                //let counter: number = 0;
                let na: any[] = [];
                let np: any[] = [];

                let a: any[] = response.content.data;

                a.forEach(d =>
                {
                    // counter = counter + 1;
                    // if (counter > 10)
                    //     return;
                    var coordinates = [
                        { latitude: d.a, longitude: d.b },
                        { latitude: d.c, longitude: d.d }
                    ];

                    let color: any = null;
                    if (d.l)
                    {
                        color = "#990000"
                    }

                    var path = {
                        paths: coordinates,
                        geodesic: true,
                        strokeColor: color ? color : '#000099',
                        strokeOpacity: 0.5,
                        strokeWeight: 2
                    };
                    np.push(path);
                    na.push({ latitude: d.a, longitude: d.b, label: d.f + ':' + d.t });
                });

                this.myLines = np;
                this.myMarkers = na;

                this.message = "Total assignemnts: " + this.myMarkers.length;
            });
```
